### ISSUE TITLE
Feature request: add a way to reference base16 colors 

### ISSUE THREAD

**Issue by shaunsingh** [SenchoPens/base16.nix#1]
First of all thank you for the project, its the best base16 nix project I've used so far. 

Would it be possible to add a way to reference the hex values in any config, by something like `${base16.base05}`?

**Comment by SenchoPens** [comment]
Thank for your kind words :)
Can you expand a bit on the feature that you need?
Maybe that's already possible, the documentation can be a bit unclear (sorry):
Right now you can reference the colors after you set the scheme like this: `config.scheme.base05`, almost like in the example with `alacritty` from `README.md`, but there we want to also have a # symbol before the colors, so we reference the colors like this `config.scheme.withHashtag.base05` (of course, if you want just single color, writing `"#${config.scheme.base05}"` is easier, because `withHashtag` was designed to be used like this: `with config.scheme.withHashtag; ...`, like in the example with `alacritty`)

**Comment by shaunsingh** [comment]
Oh I see, yup that was the feature I was looking for. Thanks for the great project once again!
